// <auto-generated />
namespace WebSmartPhone.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChinhSuaProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChinhSuaProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202311270743332_ChinhSuaProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
